SELECT * 
FROM PRODUCTS
ORDER BY unitprice DESC;

SELECT *
FROM CUSTOMERS
WHERE COUNTRY in ('UK','Spain');

SELECT * 
FROM PRODUCTS
WHERE UNITSINSTOCK >= 100
AND UNITPRICE >=25;

SELECT DISTINCT SHIPCOUNTRY
FROM ORDERS
GROUP BY SHIPCOUNTRY;

SELECT *
FROM ORDERS
WHERE ORDERDATE BETWEEN '1996-10-01' AND '1996-10-31';

SELECT * 
FROM ORDERS
WHERE SHIPCOUNTRY = 'Germany'
AND EXTRACT(YEAR FROM ORDERDATE) = 1996
AND EMPLOYEEID = 1
AND FREIGHT >= 100
AND SHIPREGION IS NULL;

SELECT *
FROM ORDERS 
WHERE SHIPPEDDATE > requireddate;

SELECT * 
FROM ORDERS
WHERE EXTRACT(YEAR FROM ORDERDATE) = 1997
AND EXTRACT(MONTH FROM ORDERDATE) BETWEEN 1 AND 4
AND SHIPCOUNTRY = 'Canada';

SELECT * 
FROM ORDERS 
WHERE EMPLOYEEID IN (2,5,8)
AND SHIPREGION IS NOT NULL
AND SHIPVIA IN (1,3)
ORDER BY EMPLOYEEID, SHIPVIA;

SELECT * 
FROM EMPLOYEES 
WHERE BIRTHDATE >= '1960-01-01'
AND REGION IS NULL;


